language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"

# Don't do CI for WIP branches
branches:
  except:
    - /^WIP-.*$/

sudo: false

setup:
  - git fetch --unshallow && git fetch --tags

script:
  - python setup.py test
  - python setup.py install
  # Check the utils run
  - litex_term --help
  - litex_server --help
  - litex_client --help || true # FIXME: AttributeError: module 'litex.soc.tools.remote.litex_client' has no attribute 'main'
  - mkmscimg --help
